# Generated by Django 3.0.8 on 2022-03-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_operaterecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaterecord',
            name='dataId',
            field=models.IntegerField(default=0),
        ),
    ]
