# Generated by Django 3.0.8 on 2022-03-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20220312_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
