# Generated by Django 3.0.8 on 2022-03-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperateRecord',
        ),
    ]
