# Generated by Django 3.0.8 on 2022-03-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_delete_operaterecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='extra_property_edit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='extra_property_edit',
            field=models.TextField(default=''),
        ),
    ]
