# Generated by Django 3.0.8 on 2022-03-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20220313_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='extra_property_edit',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='extra_property_edit',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
