# Generated by Django 3.0.8 on 2022-03-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataId', models.IntegerField(default=0)),
                ('modelName', models.CharField(max_length=64)),
                ('info', models.TextField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
                'ordering': ['-createTime'],
            },
        ),
    ]
