# Generated by Django 3.0.8 on 2022-03-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_util', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaterecord',
            name='operate',
            field=models.CharField(default='history', max_length=16),
        ),
    ]
