# Generated by Django 3.0.8 on 2022-03-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cccomment',
            name='extra_property_edit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tcomment',
            name='extra_property_edit',
            field=models.TextField(default=''),
        ),
    ]
